name: chat_pdm
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  get: ^4.3.8
  shared_preferences: ^2.0.18
  firebase_core: ^2.16.0
  firebase_database: ^10.2.6
  firebase_auth: ^4.10.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
