// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmPC-ONmB0F4tmwc3H1zBmWyFodmlxOnU',
    appId: '1:985603862781:web:d8be5fc7513e911d1b4e94',
    messagingSenderId: '985603862781',
    projectId: 'pdm3-85526',
    authDomain: 'pdm3-85526.firebaseapp.com',
    databaseURL: 'https://pdm3-85526-default-rtdb.firebaseio.com',
    storageBucket: 'pdm3-85526.appspot.com',
    measurementId: 'G-6E38M8BXZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmlvAgC4_E1X2M5spgq7Qsn5JPeDboBhw',
    appId: '1:985603862781:android:783bd47594d78de31b4e94',
    messagingSenderId: '985603862781',
    projectId: 'pdm3-85526',
    databaseURL: 'https://pdm3-85526-default-rtdb.firebaseio.com',
    storageBucket: 'pdm3-85526.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuf96tPLZulKDpS8vPjm3T-GcknAqqImw',
    appId: '1:985603862781:ios:6279f78c212a01871b4e94',
    messagingSenderId: '985603862781',
    projectId: 'pdm3-85526',
    databaseURL: 'https://pdm3-85526-default-rtdb.firebaseio.com',
    storageBucket: 'pdm3-85526.appspot.com',
    iosBundleId: 'com.example.chatPdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuf96tPLZulKDpS8vPjm3T-GcknAqqImw',
    appId: '1:985603862781:ios:d44a4d81d32070471b4e94',
    messagingSenderId: '985603862781',
    projectId: 'pdm3-85526',
    databaseURL: 'https://pdm3-85526-default-rtdb.firebaseio.com',
    storageBucket: 'pdm3-85526.appspot.com',
    iosBundleId: 'com.example.chatPdm.RunnerTests',
  );
}
